# Generated by Django 3.2.12 on 2022-06-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0002_electionarea_electiontype_candidate_electionarea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='status',
            field=models.IntegerField(choices=[(1, 'Voted'), (2, 'Not Voted')], default=2),
        ),
    ]
