# Generated by Django 3.2.12 on 2022-06-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0003_alter_voter_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Start'), (2, 'Not Start')], default=1, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='voting',
            name='status',
        ),
    ]
