# Generated by Django 3.2.12 on 2022-06-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0004_auto_20220616_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='voteemailstatus',
            field=models.IntegerField(choices=[(1, 'Voted'), (2, 'Not Voted')], default=2),
        ),
    ]
