# Generated by Django 3.2.12 on 2022-06-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0005_voter_voteemailstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='emailstatus',
            field=models.IntegerField(choices=[(1, 'Verified'), (2, 'Not Verified')], default=2),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voteemailstatus',
            field=models.IntegerField(choices=[(1, 'Verified'), (2, 'Not Verified')], default=2),
        ),
    ]
