# Generated by Django 3.2.12 on 2022-06-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0006_auto_20220616_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='winner',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='votingstatus',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Start'), (2, 'Not Start'), (3, 'Winner Announced')], default=1, null=True),
        ),
    ]
