# Generated by Django 3.2.12 on 2022-06-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0007_auto_20220623_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionarea',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
