# Generated by Django 3.2.12 on 2022-06-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0009_votingstatus_electionarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votingstatus',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Start'), (2, 'Not Start'), (3, 'Winner Announced')], default=2, null=True),
        ),
    ]
