# Generated by Django 3.2.12 on 2022-06-24 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0010_alter_votingstatus_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('winby', models.CharField(blank=True, max_length=100, null=True)),
                ('electionarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voteapp.electionarea')),
                ('electiontype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voteapp.electiontype')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voteapp.candidate')),
            ],
        ),
    ]
