# Generated by Django 3.2.12 on 2022-06-24 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0011_votinghistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingstatus',
            name='electiontype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voteapp.electiontype'),
        ),
    ]
